#Hugo configuration
title = "proje"
baseURL = "https:\/\/proje.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758904"
subfolder = ""
cookiedomain = "proje.com"
